### ISSUE TITLE
How do we run your API

### ISSUE THREAD

**Issue by hdsouza** [janlukasschroeder/tipranks-api-v2#1]
Hi Jan, 
Do we use PHP, Python or how do I run your API?
Or Is it accessible though Postman?
Thanks

**Comment by janlukasschroeder** [comment]
@hdsouza you can use Node.js to access the API. 

## Steps
- Install Node.js (which includes `npm) if you haven't already. On Mac in the command line type `brew install node`. More information here: [nodejs.org](https://nodejs.org/en)
- Set up a new Node.js project. In the command line type
  - `mkdir my-new-project && cd my-new-project` to create a new folder
  - `npm init` to scaffold the Node.js project
  - `touch index.js` to create the file `index.js`
  - `npm install tipranks-api-v2` to install the library to access the API
  - Copy/paste the example code below inside the `index.js` file
```js
const tipranksApi = require('tipranks-api-v2');
tipranksApi.getPriceTargets('MU').then(result => console.log(result));
tipranksApi.getNewsSentimentData('MU').then(result => console.log(result));
```
  - `node index.js` to run the code inside the `index.js` file
  - Done! Now you should see the price targets and the news sentiment for the ticker `MU` 
  
FYO: I just released a hot fix. The version you forked (v1.0.1) didn't work anymore. The new version (v.1.0.2) works.

Let me know if you have any other questions!

**Comment by janlukasschroeder** [comment]
@hdsouza I also just updated the documentation explaining how to use the `priceTarget` and `newsSentiment` methods of the API. See here https://github.com/janlukasschroeder/tipranks-api-v2#tiprankscom-api

**Comment by hdsouza** [comment]
Thanks Jan. Nice instructions. The script runs great.
I noticed under "Analyst ratings"  the "average price" for MU was 46.5 and the script displayed 46.77 for "mean" price. Is the script calculating this number based on separate data.
Also are you able to extract the recommendation itself like "Moderate buy"

**Comment by janlukasschroeder** [comment]
@hdsouza great to hear! 

The price calculator (e.g. mean price) only considers analyst price estimates given in the last 3 months. I intentionally excluded estimates given more than three months ago as analysts seem to review/update their estimates in a quarterly interval. I should have explained that in my documentation - I'll update now.

Re "Moderate Buy": I'll have a look, and let you know what I can do.
